name: Build Docker Image

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "action.yml"
      - "README.md"

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build .
